baseURL = "https://wizardwatch.net/"
languageCode = "en-us"
title = "wizardwatch"
theme = "ananke"
[params]
  author = ""
  favicon = ""
  site_logo = ""
  description = "My blog on my own little piece of the internet"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/wizardwatch"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  mainSections = ['blog']
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 2
